### ISSUE TITLE
No sound..

### ISSUE THREAD

**Issue by NuclearCookie** [jiborobot/atom-audio#1]
Hi! Very nice initiative. I've tried to play a local mp3 file in my project ( Just a few seconds ), yet I can't hear anything. The progress bar shows up so it looks like it reads the file correctly. Any idea? :)

OS: Ubuntu 15.01
Atom version: 1.2

**Comment by francoislaberge** [comment]
Hmmmm. Let me check it out.

**Comment by francoislaberge** [comment]
Weird. I'm not having any issues. I just updated 1.2.3. But I doubt that's the issue.

Oh, but I'm on a Mac. Maybe Atom (Electron rather) on Ubuntu doesn't come with mp3 support (requires a codec that is sort of a grey area to include with chromium type distributions).

Do you see any errors in the dev tools console?

Thanks again for reporting issues!

**Comment by NuclearCookie** [comment]
No, I only see `attached!` in the logs. Nothing else..

**Comment by francoislaberge** [comment]
Can you try playing an .ogg file as a sanity check?

On Fri, Nov 20, 2015 at 8:21 AM, Pieter Vantorre <notifications@github.com>
wrote:

> No, I only see attached! in the logs. Nothing else..
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jiborobot/atom-audio/issues/1#issuecomment-158401643>.
>



-- 
*Francois Laberge*
*Principal Robot SDK Engineer*
*Jibo <http://jibo.com>*
*Boston*
*francoislaberge.com | @francoislaberge
<http://twitter.com/francoislaberge>*

**Comment by NuclearCookie** [comment]
Oh yeah.. Worth mentioning. I have no sound on youtube, spotify etc in chrome ( some games do have sound though ). So it might be related to that since electron ses chromium if I'm not mistaken...
Woops!

**Comment by francoislaberge** [comment]
Ok, cool. Good to know.

**Comment by NuclearCookie** [comment]
So not your fault after all, closing this ;) Thanks for the swift replies

**Comment by francoislaberge** [comment]
:), my pleasure.

**Comment by NuclearCookie** [comment]
Confirmed that when I fixed my audio in chromium, This plugin worked as expected. Wonderful!
